@startmindmap
* Teamlead Roadmap
** Роли и обязанности
***_ Resource Manager
****_ Управление людьми
*****_ Найм
******_ Профиль кандидата
******_ Собеседования
******_ Онбординг
******_ Тестовый период
*****_ Увольнение
*****_ Мотивация
*****_ Развитие
*****_ Промо
******_ Ассессмент
******_ Карьерная линейка
*****_ Обратная связь
*****_ One-to-one
*****_ Административная работа
****_ Управление командой
*****_ Запуск команды
*****_ Управление компетенциями
*****_ Дизайн команды
*****_ Организация рабочего пространства
*****_ Климат в команде
*****_ Зрелость команды
*****_ Обеспечение прозрачности
****_ Развитие технического бренда
***_ Product Owner
****_ Понимание продукта
*****_ Знание рынка
*****_ Знание пользователей
*****_ Знание продукта
****_ Принятие продуктовых решений
*****_ Целеполагание
*****_ Управление продуктовым бэклогом
******_ Генерация элементов бэклога
******_ Приоритизация бэклога
***_ Integrator
****_ Знание бизнеса
****_ Корпоративная культура
****_ Структура компании
***_ Technical Lead
****_ Обеспечение качества продукта
*****_ Code Review
*****_ Тестирование
******_ Тестовая модель
******_ Тест-планы
******_ Пирамида тестирования
******_ Оптимизация количества тестирования
*****_ Работа с багами
*****_ Управление инцидентами
*****_ Метрики и мониторинг
*****_ Нефункциональные требования
****_ Обеспечение технического качества
*****_ Unit-тестирование
*****_ Чистый код
*****_ Рефакторинг
*****_ Управление техническим долгом
****_ Знание технологий
*****_ Написание кода
*****_ Знание технологического стека команды
*****_ Выбор технологий и контроль их стека
****_ Автоматизация цикла разработки
*****_ Работа с VCS
*****_ CI
*****_ Автоматизация релизов
****_ Управление знаниями
*****_ Распространение знаний
*****_ Техническая документация
****_ Архитектура
*****_ Сбор технических требований
*****_ Проектирование
*****_ Архитектурные ревью
*****_ Эволюция
****_ Capacity Management
***_ Administrator
****_ Построение цикла разработки
*****_ Получение задач
*****_ Разработка
******_ Конструирование методологии
*******_ Описание
*******_ Оценка
*******_ Движение
*******_ Контроль выполнения
******_ Готовые подходы
*******_ Scrum
*******_ Lean
*****_ Выпуск задач
******_ Приемка
******_ Раскатка
****_ Проектное управление
*****_ Конструирование методологии
*****_ Готовые подходы
******_ PMBoK
******_ PDCA
****_ Стейкхолдинг

left side

** Personal Skills
***_ Развитие себя
****_ Умение учиться
****_ Рефлексия
****_ Выработка привычек
***_ Отношения
****_ Эмпатия
****_ Эмоциональный интеллект
****_ Понимание ценности различий
***_ Мышление
****_ Системное мышление
****_ Стратегическое видение
****_ Принятие решений
***_ Стили управления
***_ Коммуникации
****_ Фасилитация
****_ Сотрудничество
****_ Управление конфликтами
****_ Дача и получение обратной связи
****_ Нетворкинг
****_ Публичные выступления
****_ Работа с текстом
***_ Тайм-менеджемент
****_ Постановка личных целей
****_ Управление временем
****_ Управление приоритетами

@endmindmap