@startmindmap
* Technical Unit Lead в Авито
** Роли и обязанности
***_ People Manager
****_ Управление людьми
*****_ Найм
******_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/profile.md Профиль кандидата]]
******_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/interview.md Собеседования]]
******_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/onboarding.md Онбординг]]
******_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/test-period.md Тестовый период]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/firing.md Увольнение]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/motivation.md Мотивация]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/development.md Развитие]]
*****_ Промо
******_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/assessment.md Ассессмент]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/feedback.md Обратная связь]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/one-to-one.md One-to-one]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/admin.md Административная работа]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/delegation.md Делегирование]]
****_ Управление командой
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/team-launch.md Запуск команды]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/competency-management.md Управление компетенциями]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/team-design.md Дизайн команды]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/workspace.md Организация рабочего пространства]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/team-climate.md Климат в команде]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/team-maturity.md Зрелость команды]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/resource-manager/transparency.md Обеспечение прозрачности]]
***_ Product Owner
****_ Понимание продукта
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/product-owner/market-knowledge.md Знание рынка]]
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/product-owner/user-knowledge.md Знание пользователей]]

left side

** Роли и обязанности
***_ Technical Lead
****_ Обеспечение качества продукта
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/technical-lead/code-review.md Code Review]]
*****_ Тестирование
******_ Тестовая модель
******_ Тест-планы
******_ Пирамида тестирования
******_ Оптимизация количества тестирования
*****_ Работа с багами
*****_ Управление инцидентами
*****_ Метрики и мониторинг
*****_ Нефункциональные требования
****_ Обеспечение технического качества
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/technical-lead/unit-testing.md Unit-тестирование]]
*****_ Чистый код
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/technical-lead/refactoring.md Рефакторинг]]
*****_ Управление техническим долгом
****_ Знание технологий
*****_ [[https://github.com/tlbootcamp/tlroadmap/blob/master/skills/technical-lead/code.md Написание кода]]
*****_ Знание технологического стека команды
****_ Архитектура
*****_ Сбор технических требований
*****_ Проектирование
*****_ Архитектурные ревью
*****_ Эволюция
***_ Administrator
****_ Построение цикла разработки
*****_ Разработка
******_ Готовые подходы
*******_ Scrum
****_ Стейкхолдинг

@endmindmap